name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build docker image
      run: docker build . --file Dockerfile --tag ushasrishetty/to-do-app-assignment:$(date + %s)
    - name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/to-do-app-assignment

    
        
   
